import { useState, createContext } from 'react'

export const ArtistsContext = createContext()

export const ArtistsProvider = ({ children }) => {

    const [artists, setArtists] = useState([
        {
            id: 'artist1',
            slug: 'lazza',
            artistName: 'Lazza',
            image: require('../images/pictures/lazza.jpeg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 3,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist2',
            slug: 'thasup',
            artistName: 'thasup',
            image: require('../images/pictures/thasup.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 3,
            highlight: true,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist3',
            slug: 'artie-5ive',
            artistName: 'Artie 5ive',
            image: require('../images/pictures/artie-5ive.jpeg'),
            flashLeaderboard: {
                status: undefined,
            }, 
            importance: 3,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist4',
            slug: 'suspect-cb',
            artistName: 'Suspect CB',
            image: require('../images/pictures/suspect-cb.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist5',
            slug: 'astro',
            artistName: 'Astro',
            image: require('../images/pictures/astro.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 2,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist6',
            slug: 'alfa',
            artistName: 'Alfa',
            image: require('../images/pictures/alfa.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 2,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist7',
            slug: 'sick-luke',
            artistName: 'Sick Luke',
            image: require('../images/pictures/sick-luke.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist8',
            slug: 'nabi',
            artistName: 'Nabi',
            image: require('../images/pictures/nabi.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist9',
            slug: 'mezzosangue',
            artistName: 'Mezzosangue',
            image: require('../images/pictures/mezzosangue.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist10',
            slug: 'anna',
            artistName: 'ANNA',
            image: require('../images/pictures/anna.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 2,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist11',
            slug: 'gue',
            artistName: 'Guè',
            image: require('../images/pictures/gue.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist12',
            slug: 'marracash',
            artistName: 'Marracash',
            image: require('../images/pictures/marracash.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist13',
            slug: 'sfera-ebbasta',
            artistName: 'Sfera Ebbasta',
            image: require('../images/pictures/sfera-ebbasta.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 3,
            highlight: true,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist14',
            slug: 'coma-cose',
            artistName: 'Coma_cose',
            image: require('../images/pictures/coma_cose.jpeg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist15',
            slug: 'salmo',
            artistName: 'Salmo',
            image: require('../images/pictures/salmo.jpeg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist16',
            slug: 'mara-sattei',
            artistName: 'Mara Sattei',
            image: require('../images/pictures/mara-sattei.jpeg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 2,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist17',
            slug: 'don-pero',
            artistName: 'Don Pero',
            image: require('../images/pictures/don-pero.jpeg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist18',
            slug: 'olly',
            artistName: 'Olly',
            image: require('../images/pictures/olly.jpeg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist19',
            slug: 'venerus',
            artistName: 'Venerus',
            image: require('../images/pictures/venerus.jpeg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 2,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist20',
            slug: 'nitro',
            artistName: 'Nitro',
            image: require('../images/pictures/nitro.jpeg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist21',
            slug: 'maneskin',
            artistName: 'Maneskin',
            image: require('../images/pictures/maneskin.jpeg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist22',
            slug: 'gionny-scandal',
            artistName: 'GionnyScandal',
            image: require('../images/pictures/gionny-scandal.jpeg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist23',
            slug: 'sadturs',
            artistName: 'Sadturs',
            image: require('../images/pictures/sadturs.jpeg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist24',
            slug: 'rose-villain',
            artistName: 'Rose Villain',
            image: require('../images/pictures/rose-villain.jpeg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist25',
            slug: 'mace',
            artistName: 'MACE',
            image: require('../images/pictures/mace.jpeg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist26',
            slug: 'ghali',
            artistName: 'Ghali',
            image: require('../images/pictures/ghali.jpeg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist27',
            slug: 'kid-yugi',
            artistName: 'Kid Yugi',
            image: require('../images/pictures/kid-yugi.jpeg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 2,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist28',
            slug: 'drefgold',
            artistName: 'DrefGold',
            image: require('../images/pictures/drefgold.jpeg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 2,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist29',
            slug: 'miles',
            artistName: 'MILES',
            image: require('../images/pictures/miles.jpeg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: true,
            chatIsActive: true,
        },{
            id: 'artist30',
            slug: 'billie-eilish',
            artistName: 'Billie Eilish',
            image: require('../images/pictures/billie_eilish.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: false,
            chatIsActive: true,
        },{
            id: 'artist31',
            slug: '21-savage',
            artistName: '21 Savage',
            image: require('../images/pictures/21_savage.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: false,
            chatIsActive: true,
        },{
            id: 'artist32',
            slug: 'future',
            artistName: 'Future',
            image: require('../images/pictures/future.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: false,
            chatIsActive: true,
        },{
            id: 'artist33',
            slug: 'travis-scott',
            artistName: 'Travis Scott',
            image: require('../images/pictures/travis_scott.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: false,
            chatIsActive: true,
        },{
            id: 'artist34',
            slug: 'nirvana',
            artistName: 'Nirvana',
            image: require('../images/pictures/nirvana.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: false,
            chatIsActive: true,
        },{
            id: 'artist35',
            slug: 'stray-kids',
            artistName: 'Stray Kids',
            image: require('../images/pictures/stray_kids.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: false,
            chatIsActive: true,
        },{
            id: 'artist36',
            slug: 'eminem',
            artistName: 'Eminem',
            image: require('../images/pictures/eminem.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: false,
            chatIsActive: true,
        },{
            id: 'artist37',
            slug: 'laura-pausini',
            artistName: 'Laura Pausini',
            image: require('../images/pictures/laura_pausini.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: false,
            chatIsActive: true,
        },{
            id: 'artist38',
            slug: 'bnkr44',
            artistName: 'bnkr44',
            image: require('../images/pictures/bnkr44.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: false,
            chatIsActive: true,
        },{
            id: 'artist39',
            slug: 'okgiorgio',
            artistName: 'okgiorgio',
            image: require('../images/pictures/okgiorgio.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: false,
            chatIsActive: true,
        },{
            id: 'artist40',
            slug: 'nayt',
            artistName: 'Nayt',
            image: require('../images/pictures/nayt.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: false,
            chatIsActive: true,
        },{
            id: 'artist41',
            slug: 'fedez',
            artistName: 'Fedez',
            image: require('../images/pictures/fedez.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: false,
            chatIsActive: true,
        },{
            id: 'artist42',
            slug: 'irama',
            artistName: 'Irama',
            image: require('../images/pictures/irama.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: false,
            chatIsActive: true,
        },{
            id: 'artist43',
            slug: 'achille-lauro',
            artistName: 'Achille Lauro',
            image: require('../images/pictures/achille-lauro.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: false,
            chatIsActive: true,
        },{
            id: 'artist44',
            slug: 'serena-brancale',
            artistName: 'Serena Brancale',
            image: require('../images/pictures/serena-brancale.jpg'),
            flashLeaderboard: {
                status: undefined,
            },
            importance: 1,
            highlight: false,
            verified: false,
            chatIsActive: true,
        }
    ])

    return (
        <ArtistsContext.Provider value={{ artists, setArtists }}>
            {children}
        </ArtistsContext.Provider>
    )
}